#----------------------------------------------------------
#   ____            _          _    _ _
#  | __ )  __ _ ___| |__      / \  | (_) __ _ ___  ___  ___
#  |  _ \ / _` / __| '_ \    / _ \ | | |/ _` / __|/ _ \/ __|
#  | |_) | (_| \__ \ | | |  / ___ \| | | (_| \__ \  __/\__ \
#  |____/ \__,_|___/_| |_| /_/   \_\_|_|\__,_|___/\___||___/
#
#----------------------------------------------------------
# This file contains some custom bash aliases
# some are convienent shortcut while some are safety measure
# this still doesn't prevent you from removing french /s
#----------------------------------------------------------

#if [ -f ~/.bash_aliases ]; then
#    . ~/.bash_aliases
#fi

#----------------------------------------------------------
# launch tmux in any bash terminal emulator
# if command -v tmux &> /dev/null && [ -n "$PS1" ] && [[ ! "$TERM" =~ screen ]] && [[ ! "$TERM" =~ tmux ]] && [ -z "$TMUX" ]; then
#   exec tmux
# fi

# alias for apt operations
alias in='sudo apt install'
alias up='sudo apt update && sudo apt upgrade -y'
alias fup='sudo apt update && sudo apt full-upgrade -y'
alias autorm='sudo apt autoremove && sudo apt autoclean && sudo apt clean'
alias aptrm='sudo apt remove'
#----------------------------------------------------------

#----------------------------------------------------------
# some terminal shortcut
# allow the creation of subdirectories
alias mkdir='mkdir -pv'

# allow interactive mode
alias mv='mv -i'
alias cp='cp -i'
alias rm='rm -i'

# alias for git auto detect changes and commit plus push
alias submit='git add . && git commit -a && git push'
#----------------------------------------------------------

#----------------------------------------------------------
# alias for apps
alias v='nvim'
alias nf='neofetch'
alias dmenu="dmenu_run -p 'run' -l 3"
#----------------------------------------------------------

#----------------------------------------------------------
# alias for system information call
alias gg='sudo poweroff'
alias cl='clear'
#----------------------------------------------------------

#----------------------------------------------------------
# Variable exports
export GOPATH=$HOME/go
export PATH=${PATH}:$HOME/go/bin
export TERM=xterm-256color
#----------------------------------------------------------
# EOF
#----------------------------------------------------------
